# Generated by Django 6.0.2 on 2026-02-09 14:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('factors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('analyzing', 'Analyzing'), ('completed', 'Completed'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('ai_confidence', models.FloatField(blank=True, null=True)),
                ('ai_explanation', models.TextField(blank=True)),
                ('ai_insights', models.JSONField(blank=True, default=list)),
                ('analyzed_at', models.DateTimeField(blank=True, null=True)),
                ('chosen_at', models.DateTimeField(blank=True, null=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('reminder_enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'decisions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DecisionFactor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('weight', models.FloatField(default=0.5)),
                ('is_ai_suggested', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decision_factors', to='decisions.decision')),
                ('factor_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='factors.factortemplate')),
            ],
            options={
                'db_table': 'decision_factors',
                'ordering': ['-weight', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DecisionOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('pros', models.JSONField(blank=True, default=list)),
                ('cons', models.JSONField(blank=True, default=list)),
                ('ai_score', models.FloatField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='decisions.decision')),
            ],
            options={
                'db_table': 'decision_options',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='decision',
            name='ai_recommendation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommended_for', to='decisions.decisionoption'),
        ),
        migrations.AddField(
            model_name='decision',
            name='chosen_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chosen_for', to='decisions.decisionoption'),
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reflection', models.TextField(blank=True)),
                ('satisfaction', models.FloatField(blank=True, null=True)),
                ('outcome_notes', models.TextField(blank=True)),
                ('lessons_learned', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decision', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entry', to='decisions.decision')),
            ],
            options={
                'db_table': 'journal_entries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FactorRating',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.FloatField()),
                ('notes', models.TextField(blank=True)),
                ('decision_factor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='decisions.decisionfactor')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factor_ratings', to='decisions.decisionoption')),
            ],
            options={
                'db_table': 'factor_ratings',
                'unique_together': {('decision_factor', 'option')},
            },
        ),
    ]
